export type City = {
  city: string;
  districts: string[];
};

export const cities: City[] = [
  {
    city: 'Lefkoşa',
    districts: [
      'Akıncılar',
      'Alayköy',
      'Balıkesir',
      'Beyköy',
      'Cihangir',
      'Çağlayan',
      'Çukurova',
      'Değirmenlik',
      'Demirhan',
      'Dilekkaya',
      'Dumlupınar',
      'Düzova',
      'Erdemli',
      'Gaziköy',
      'Gelibolu',
      'Göçmenköy',
      'Gökhan',
      'Gönyeli',
      'Gürpınar',
      'Hamitköy',
      'Haspolat',
      'Kalavaç',
      'Kanlıköy',
      'Kırklar',
      'Kızılbaş',
      'Köşklüçiftlik',
      'Kumsal',
      'Küçük Kaymaklı',
      'Lefkoşa Surlariçi',
      'Marmara',
      'Meriç',
      'Metehan',
      'Minareliköy',
      'Ortaköy',
      'Sanayi Bölgesi',
      'Taşkınköy',
      'Türkeli',
      'Yeniceköy',
      'Yenikent',
      'Yenişehir',
      'Yılmazköy',
    ],
  },
  {
    city: 'Girne',
    districts: [
      'Ağırdağ',
      'Akçiçek',
      'Akdeniz',
      'Alagadi',
      'Alemdağ',
      'Alsancak',
      'Arapköy',
      'Aşağı Girne',
      'Bahçeli',
      'Bellapais',
      'Beşparmak',
      'Boğaz',
      'Çamlıbel',
      'Çatalköy',
      'Dağyolu',
      'Dikmen',
      'Doğanköy',
      'Edremit',
      'Esentepe',
      'Geçitköy',
      'Girne Merkez',
      'Göçeri',
      'Hisarköy',
      'Ilgaz',
      'İncesu',
      'Karaağaç',
      'Karakum',
      'Karaoğlanoğlu',
      'Karmi',
      'Karşıyaka',
      'Kayalar',
      'Kılıçarslan',
      'Koruçam',
      'Kozan',
      'Kömürcü',
      'Lapta',
      'Malatya',
      'Ozanköy',
      'Pınarbaşı',
      'Sadrazamköy',
      'Şirinevler',
      'Taşkent',
      'Tepebaşı',
      'Türk Mahallesi',
      'Yeşiltepe',
      'Yukarı Girne',
      'Zeytinlik',
    ],
  },
  {
    city: 'Gazimağusa',
    districts: [
      'Akdoğan',
      'Akova',
      'Alaniçi',
      'Arıdamı',
      'Aslanköy',
      'Atlılar',
      'Baykal',
      'Beyarmudu',
      'Çanakkale',
      'Çınarlı',
      'Dörtyol',
      'Dumlupınar',
      'Geçitkale',
      'Gönendere',
      'Gülseren',
      'Güvercinlik',
      'İnönü',
      'Kaleiçi',
      'Karakol',
      'Korkuteli',
      'Kurudere',
      'Kuzucuk',
      'Küçük Erenköy',
      'Mağusa Merkez',
      'Mallıdağ',
      'Maraş',
      'Mormenekşe',
      'Mutluyaka',
      'Paşaköy',
      'Pınarlı',
      'Pirhan',
      'Sakarya',
      'Salamis',
      'Serdarlı',
      'Tatlısu',
      'Turunçlu',
      'Tuzla',
      'Türkmenköy',
      'Ulukışla',
      'Vadili',
      'Yamaçköy',
      'Yeni Boğaziçi',
      'Yıldırım',
    ],
  },
  {
    city: 'Guzelyurt',
    districts: [
      'Akçay',
      'Aşağı Bostancı',
      'Aydınköy',
      'Cengizköy',
      'Güzelyurt Merkez',
      'Kalkanlı',
      'Serhatköy',
      'Yayla',
      'Yukarı Bostancı',
      'Zümrütköy',
    ],
  },
  {
    city: 'Iskele',
    districts: [
      'Ağıllar',
      'Altınova',
      'Ardahan',
      'Avtepe',
      'Aygün',
      'Bafra',
      'Bahçeler',
      'Balalan',
      'Bogaziçi',
      'Boğaz',
      'Boğaztepe - Monarga',
      'Boltaşlı',
      'Büyükkonuk',
      'Çayırova',
      'Derince',
      'Dipkarpaz',
      'Ergazi',
      'Esenköy',
      'İskele Merkez',
      'Kaleburnu',
      'Kalecik',
      'Kantara',
      'Kaplıca',
      'Kilitkaya',
      'Kumyalı',
      'Kurtuluş',
      'Kuruova',
      'Kuzucuk',
      'Long Beach',
      'Mehmetçik',
      'Mersinlik',
      'Ötüken',
      'Pamuklu',
      'Sazlıköy',
      'Sınırüstü',
      'Sipahi',
      'Taşlıca',
      'Topçuköy',
      'Turnalar',
      'Tuzluca',
      'Yarköy',
      'Yedikonuk',
      'Yeni Erenköy',
      'Yeşilköy',
      'Ziyamet',
    ],
  },
  {
    city: 'Lefke',
    districts: [
      'Doğancı',
      'Gaziveren',
      'Gemikonağı',
      'Lefke',
      'Yedidalga',
      'Yeşilırmak',
      'Yeşilyurt',
    ],
  },
];
